### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by R3alflash** [hyperion-project/HyperBian#2]
Hey,

is there any workaround to update the "HyperBian" OS?

Ty

**Comment by Paulchen-Panther** [comment]
I think it only helps reinstall. Have you tried sudo dpkg link_to_hyperion.deb?
@brindosch

**Comment by R3alflash** [comment]
sry, i think u havent unterstand me.

I mean this OS https://github.com/hyperion-project/HyperBian

How can i update this?

**Comment by tpmodding** [comment]
Definiere Update bitte

**Comment by Paulchen-Panther** [comment]
> this is the result:
> 
> `dpkg: Fehler: Auf das Archiv »hyperion.deb« kann nicht zugegriffen werden: Datei oder Verzeichnis nicht gefunden`

You should actually be clear that the command is not working. The Hyperion.deb file does not yet exist. You should first [download them from GitHub](https://github.com/hyperion-project/hyperion.ng/releases).

**Comment by R3alflash** [comment]
> Definiere Update bitte

Aktuell ist Version 7 verfügbar, die HyperBian Version beinhaltet aber Version 6.

I will try to download the new file and test it. Ty

**Comment by Paulchen-Panther** [comment]
> Aktuell ist Version 7 verfügbar, die HyperBian Version beinhaltet aber Version 6.

Kann ich so nicht unterschreiben. Es befindet sich im aktuellen Image immer die neuste Version:
Proof: https://prnt.sc/ts6k3q

**Comment by R3alflash** [comment]
> Es befindet sich im aktuellen Image immer die neuste Version:
Proof: https://prnt.sc/ts6k3q
Ja sicher, da hast du recht. Allerdings hatte ich bis eben das vorherige Image noch drauf und da war die Version 6 drin. Ich will doch nicht ständig ein neues Image kopieren müssen, nur um das Update durchzuführen.
BTW Habe ich gestern probiert die neuste Version laut Anleitung zu kompilieren auf dem Pi, allerdings ging das schief, sodass es komplett neu machen musste.

**Comment by Paulchen-Panther** [comment]
Hast du das Update versucht?

**Comment by R3alflash** [comment]
Leider nein, da das kompilieren nicht geklappt hat und Hyperion garnicht mehr lief, habe ich gleich ein neues Image genommen 😅

**Comment by Paulchen-Panther** [comment]
OK. Dann schließe ich dieses Issue jetzt mal. Sollte es bei der nächsten Version beim aktualisieren zu Problemen kommen, einfach wieder öffnen.
