### ISSUE TITLE
downgrading the hyperion version from 7 to 6

### ISSUE THREAD

**Issue by sergoo-lbt** [hyperion-project/HyperBian#3]
Dear developers! Can I downgrade hyperion from 7 to 6 while on a hyperbian image? Is this even possible? Thank you for your work! You guys are amazing!

**Comment by Paulchen-Panther** [comment]
Download the Alpha 6 .deb file here and install it with dpkg.
I hope it helps.

**Comment by sergoo-lbt** [comment]
> Download the Alpha 6 .deb file [here ](https://github.com/hyperion-project/hyperion.ng/releases/tag/2.0.0-alpha.6)and install it with dpkg.
> I hope it helps.

Thank you so much for your response! Unfortunately, I'm not very good at this. I had enough strength to install the image, I'm afraid I don't know how to proceed, what dpkg is, and what version I need to download.

**Comment by Paulchen-Panther** [comment]
> > Download the Alpha 6 .deb file [here ](https://github.com/hyperion-project/hyperion.ng/releases/tag/2.0.0-alpha.6)and install it with dpkg.
> > I hope it helps.
> 
> Thank you so much for your response! Unfortunately, I'm not very good at this. I had enough strength to install the image, I'm afraid I don't know how to proceed, what dpkg is, and what version I need to download.
> Maybe there is some script for downgrading the version?

Are you ready to access your PI using SSH?

**Comment by sergoo-lbt** [comment]
> > > Download the Alpha 6 .deb file [here ](https://github.com/hyperion-project/hyperion.ng/releases/tag/2.0.0-alpha.6)and install it with dpkg.
> > > I hope it helps.
> > 
> > 
> > Thank you so much for your response! Unfortunately, I'm not very good at this. I had enough strength to install the image, I'm afraid I don't know how to proceed, what dpkg is, and what version I need to download.
> > Maybe there is some script for downgrading the version?
> 
> Are you ready to access your PI using SSH?

Yes, of course! Ssh and sftp.

**Comment by sergoo-lbt** [comment]
Read a little! I need to run sudo dpkg-i hyperion.deb by downloading it? I don't understand just where to move the downloaded hyperion.deb file?

**Comment by Paulchen-Panther** [comment]
You install hyperion with dpkg -i ...
Just imagine the deb file is a setup file under windows.

**Comment by sergoo-lbt** [comment]
> You install hyperion with dpkg -i ...
> Just imagine the deb file is a setup file under windows.

I was installing a hyperbian image... Just recorded it on the card and set up wifi and ssh according to the instructions.

**Comment by Paulchen-Panther** [comment]
I'll make you an alpha 6 build. So far there doesn't seem to be a user-friendly solution

**Comment by sergoo-lbt** [comment]
> I'll make you an alpha 6 build. So far there doesn't seem to be a user-friendly solution

Thank you very much! This is just great!

**Comment by sergoo-lbt** [comment]
> I'll make you an alpha 6 build. So far there doesn't seem to be a user-friendly solution

I'm sorry, friend! Where and when can I download it?

**Comment by Paulchen-Panther** [comment]
I'm still in the process of creating the release. Please be patient

**Comment by sergoo-lbt** [comment]
> I'm still in the process of creating the release. Please be patient

Oh! I apologize again for bothering you! May luck be on your side. Always!

**Comment by Paulchen-Panther** [comment]
Unfortunately I have to disappoint you. Alpha 6 does not run on Hyperbian. Since this is based on Raspbian OS (Debian Buster).
https://prnt.sc/ug8s6s

The implementation for the newly introduced BCM devices are unfortunately only available from Alpha 7.
https://prnt.sc/ug8sba

I'm trying to compile a current version for you. Another question, why did you want to switch from Alpha 7 to Alpha 6?

**Comment by sergoo-lbt** [comment]
> Unfortunately I have to disappoint you. Alpha 6 does not run on Hyperbian. Since this is based on Raspbian OS (Debian Buster).
> https://prnt.sc/ug8s6s
> 
> The implementation for the newly introduced BCM devices are unfortunately only available from Alpha 7.
> https://prnt.sc/ug8sba
> 
> I'm trying to compile a current version for you. Another question, why did you want to switch from Alpha 7 to Alpha 6?

Thank you for your efforts anyway! I wanted to switch to alpha 6 because static colors don't work on 7. Instead, only the flickering of LEDs in all colors. But the repetition of colors from the TV picture works fine.

**Comment by Paulchen-Panther** [comment]
Ready to install? 😃 
https://github.com/Paulchen-Panther/HyperBian/releases

**Comment by sergoo-lbt** [comment]
> Ready to install? 😃
> https://github.com/Paulchen-Panther/HyperBian/releases

You did it after all! I am very happy! Thanks! Unfortunately I'm at work now! I will definitely install it tomorrow!!! Have a nice day!

**Comment by Paulchen-Panther** [comment]
NP. Lass dir Zeit. 😄

**Comment by sergoo-lbt** [comment]
> Ready to install? 😃
> https://github.com/Paulchen-Panther/HyperBian/releases

My friend! I installed your image and it works perfectly for me! 🥳My gratitude knows no bounds!!! 🙏🏻🤝Only one question remains, is this still beta 7? Or 6? In my settings, it is displayed as beta 7...

**Comment by Paulchen-Panther** [comment]
It ist Alpha 7. Current git master.
Can we close this issue with this?

**Comment by sergoo-lbt** [comment]
> It ist Alpha 7. Current git master.
> Can we close this issue with this?

I understand! Thank you again!!! Yes, of course! I'm closing...
