### ISSUE TITLE
Hyperbian and Lightpack setup

### ISSUE THREAD

**Issue by MichaelSchemmer** [hyperion-project/HyperBian#4]
Hi there,

I'm trying to setup Hyperian using the HyperBian image on a RPi3. I'd like to connect it to a LightPack v1. So it would be Kodi sending data from a Shield to HyperBian and then to the LightPack. I have a few questions regarding setup:

1) Is the Wifi quick enough on the RPi3 to process data from Kodi?
2) I've installed it before and after booting the RPi, the lightpacks hub goes blue, but no lights turn on with the boot test pattern from HyperBian. Do I need to do anything else in the config of the lightpack to set it up using the Andromeda pattern?
3) Would it be better to install the custom firmware from https://www.reddit.com/r/Lightpack/comments/2e6wm4/modified_firmware_with_blue_lights_off/ ?
4) How is the Andromeda pattern for the lightpack configured in the HyperBian GUI
5) How many LEDs should it be configure with ie the Hardware LED count? I have 10 strips containing 3 lights, so should it be 10 or 30?
6) What should the RGB byte order be set to?
5) Some users have suggested using "" in the Serial Number field. What should it be set to?
6) And the Latch and Refresh time, can these be left at their defaults?

**Comment by tpmodding** [comment]
Hi,

this is all related to hyperion.ng itself, and has nothing to do with the image...

I would kindly ask you to open a thread in our forum to get support and answers for your questions.
Thank you!

https://hyperion-project.org/
